'use client';

import { useEffect, useMemo, useState } from 'react';
import { geoEquirectangular, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import { AlertTriangle, BarChart3, Bell, CheckCircle2, CircleHelp, FileText, Globe2, Home, Mail, MapPin, Plane, Search, Settings, Shield, Sparkles, Star, Trash2, Upload, UserRound, X, type LucideIcon } from 'lucide-react';
import { alerts, cities, countries as fallbackCountries } from '@/lib/data';
import { missingDocuments } from '@/lib/report';
import { riskCategoryLabels } from '@/lib/risk-engine';
import type { Alert, CityProfile, CountryProfile, RiskLevel, RiskScore, Trip, TripDocument, TripReport } from '@/lib/types';

type WorldFeature = { type: 'Feature'; id?: string | number; properties: { name: string }; geometry: unknown };
type FeatureCollection = { features: WorldFeature[] };
type ViewName = 'Dashboard' | 'Risk Map' | 'Countries' | 'Cities' | 'Alerts' | 'Itineraries' | 'Reports' | 'Travel Feed' | 'Support' | 'Settings';
type ProviderStatus = { key: string; name: string; category: string; status: string; notes: string; envVars: string[] };
type HoverPopup = { x: number; y: number; title: string; level: RiskLevel | 'Unknown'; score?: number; overview: string; meta?: string } | null;
type BriefTarget = { type: 'country'; country: CountryProfile } | { type: 'city'; city: CityProfile; country: CountryProfile | null } | null;
type AiStatus = { configured: boolean; provider: string; model: string; status: string };

const nav: Array<[ViewName, LucideIcon]> = [
  ['Dashboard', Home], ['Risk Map', Globe2], ['Countries', MapPin], ['Cities', Search], ['Alerts', Bell], ['Itineraries', Plane], ['Reports', FileText], ['Travel Feed', BarChart3], ['Support', CircleHelp], ['Settings', Settings]
];

const colorByLevel: Record<RiskLevel | 'Unknown', string> = { Low: '#63b86f', Moderate: '#f6c343', High: '#f97316', Critical: '#f04438', Unknown: '#253442' };
const countryNameAliases: Record<string, string> = { 'United Kingdom': 'GB', France: 'FR', Kenya: 'KE', Ukraine: 'UA', Japan: 'JP', 'United States of America': 'US', Russia: 'RU', Syria: 'SY' };
const alertCoordinates: Record<string, [number, number]> = { France: [2.3522, 48.8566], Kenya: [36.8219, -1.2921], Ukraine: [30.5234, 50.4501], Japan: [139.6503, 35.6762] };
const categoryFeeds = ['Critical Security Alerts', 'Political / Civil Unrest', 'Terrorism / Conflict', 'Health / Medical', 'Natural Hazards', 'Travel Disruption', 'Aviation / Airport Issues', 'Live Travel Intelligence'];
const tripSteps = ['Destination', 'Dates', 'Traveller profile', 'Accommodation', 'Flights / routes / meetings', 'Documents', 'Risk assessment', 'Report'];
const documentTypes = ['flights', 'visa', 'hotel booking', 'insurance', 'passport metadata', 'emergency contacts', 'medical documents'];

function scoreFor(profile?: CountryProfile | CityProfile | null) { return profile?.risk.find((risk) => risk.category === 'overall'); }
function categoryLabel(category: string) { return (riskCategoryLabels as Record<string, string>)[category] ?? category; }
function highCriticalAlerts() { return alerts.filter((alert) => ['High', 'Critical'].includes(alert.severity)); }
function profileForAlert(alert: Alert, countryList: CountryProfile[]) { return { country: countryList.find((country) => country.name === alert.country) ?? fallbackCountries.find((country) => country.name === alert.country) ?? null, city: cities.find((city) => city.name === alert.city) ?? null }; }
function countryByMapName(name: string, countryList: CountryProfile[]) { return countryList.find((country) => country.iso2 === countryNameAliases[name] || country.name === name) ?? null; }
function countryForCity(city: CityProfile, countryList: CountryProfile[]) { return countryList.find((country) => country.iso2 === city.countryIso2) ?? fallbackCountries.find((country) => country.iso2 === city.countryIso2) ?? null; }
function sourceStatusLabel(status?: string) { if (status === 'live') return 'Live provider'; if (status === 'limited') return 'Public data'; if (status === 'manual_override') return 'Manual admin input'; return 'Demo fallback'; }
function latestScore(profile?: CountryProfile | CityProfile | null) { return profile?.risk[0]?.lastUpdated ?? new Date().toISOString(); }
function advisoryFor(country?: CountryProfile | null) { const alert = country ? alerts.find((item) => item.country === country.name) : null; return alert?.title ?? country?.recommendation ?? 'No current live advisory connected'; }
function keyIssue(country?: CountryProfile | null) { const score = scoreFor(country); if (!country) return 'Limited verified data available'; if ((score?.value ?? 0) >= 75) return country.terrorismConflictOverview; if ((score?.value ?? 0) >= 50) return country.crimeOverview; return country.naturalHazards; }
function travelMeaning(score?: RiskScore) { if (!score) return 'Use baseline precautions until verified intelligence is connected.'; if (score.value >= 75) return 'Travel should be avoided or supported by specialist security and medical planning.'; if (score.value >= 50) return 'Travel is possible with enhanced planning, vetted movement and active alert monitoring.'; if (score.value >= 25) return 'Travel is generally manageable with sensible precautions and disruption monitoring.'; return 'Standard travel precautions are usually sufficient.'; }

function useCountryCatalog() {
  const [countryList, setCountryList] = useState<CountryProfile[]>(fallbackCountries);
  useEffect(() => {
    fetch('/api/countries').then((response) => response.json()).then((json) => Array.isArray(json.data) && setCountryList(json.data)).catch(() => setCountryList(fallbackCountries));
  }, []);
  return countryList;
}

function useWorld() {
  const [world, setWorld] = useState<FeatureCollection | null>(null);
  useEffect(() => {
    fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json')
      .then((response) => response.json())
      .then((topology) => setWorld(feature(topology, topology.objects.countries) as unknown as FeatureCollection))
      .catch(() => setWorld(null));
  }, []);
  return world;
}

function WorldMap({ mode, countries, selectedCity, onCountry, onCity, onAlertClick }: { mode: 'dashboard' | 'risk'; countries: CountryProfile[]; selectedCity?: CityProfile | null; onCountry?: (country: CountryProfile | null, rawName: string) => void; onCity?: (city: CityProfile) => void; onAlertClick?: (alert: Alert) => void }) {
  const world = useWorld();
  const [popup, setPopup] = useState<HoverPopup>(null);
  const projection = useMemo(() => geoEquirectangular().fitSize([980, 500], { type: 'Sphere' }), []);
  const path = useMemo(() => geoPath(projection), [projection]);
  const importantCities = cities.filter((city) => (scoreFor(city)?.value ?? 0) >= 50);
  const selectedPoint = selectedCity ? projection([selectedCity.lon, selectedCity.lat]) : null;

  return <div className="map-stage" data-map-mode="2d-flat"><svg viewBox="0 0 980 500" role="img" aria-label={mode === 'dashboard' ? '2D executive high risk event map' : '2D full country risk map'}>
    <path d={path({ type: 'Sphere' }) ?? ''} fill="#07111b" />
    {world?.features.map((item) => {
      const profile = countryByMapName(item.properties.name, countries);
      const score = scoreFor(profile);
      const level = score?.level ?? 'Unknown';
      const centroid = path.centroid(item as never);
      return <path key={`${item.id}-${item.properties.name}`} className="country" d={path(item as never) ?? ''} fill={mode === 'risk' ? colorByLevel[level] : '#1c2a36'} opacity={mode === 'risk' ? (level === 'Unknown' ? 0.42 : 0.86) : 0.5} onMouseEnter={() => mode === 'risk' && setPopup({ x: centroid[0], y: centroid[1], title: profile?.name ?? item.properties.name, level, score: score?.value, overview: profile?.securityOverview ?? 'Limited verified data available. Connect providers for a full country profile.', meta: sourceStatusLabel(score?.sourceStatus) })} onMouseLeave={() => setPopup(null)} onClick={() => mode === 'risk' && onCountry?.(profile, item.properties.name)} />;
    })}
    {mode === 'dashboard' ? highCriticalAlerts().map((alert) => {
      const point = projection(alertCoordinates[alert.country] ?? [0, 0]);
      if (!point) return null;
      return <circle key={alert.id} className="event-marker" cx={point[0]} cy={point[1]} r={alert.severity === 'Critical' ? 8 : 6} fill={colorByLevel[alert.severity]} onMouseEnter={() => setPopup({ x: point[0], y: point[1], title: `${alert.city ?? 'Major city'}, ${alert.country}`, level: alert.severity, overview: `${alert.title}. ${alert.recommendedAction}`, meta: `${new Date(alert.timestamp).toLocaleString()} - ${alert.source}` })} onMouseLeave={() => setPopup(null)} onClick={() => onAlertClick?.(alert)} />;
    }) : null}
    {mode === 'risk' ? importantCities.map((city) => {
      const point = projection([city.lon, city.lat]);
      if (!point) return null;
      const score = scoreFor(city);
      const level = score?.level ?? 'Moderate';
      return <circle key={city.id} className="city-marker" cx={point[0]} cy={point[1]} r="5" fill={colorByLevel[level]} onMouseEnter={() => setPopup({ x: point[0], y: point[1], title: `${city.name}, ${countryForCity(city, countries)?.name ?? city.countryIso2}`, level, score: score?.value, overview: city.overview, meta: sourceStatusLabel(score?.sourceStatus) })} onMouseLeave={() => setPopup(null)} onClick={() => onCity?.(city)} />;
    }) : null}
    {selectedPoint ? <circle cx={selectedPoint[0]} cy={selectedPoint[1]} r="9" fill="#f0c96b" stroke="#05080d" strokeWidth="3" /> : null}
  </svg>{popup ? <div className="map-popup" data-testid="map-hover-popup" style={{ left: `${Math.min(popup.x + 14, 760)}px`, top: `${Math.max(popup.y - 40, 12)}px` }}><strong>{popup.title}</strong><span className="severity">{popup.level} {popup.score ?? '--'}/100</span><p>{popup.overview}</p>{popup.meta ? <small>{popup.meta}</small> : null}</div> : null}</div>;
}

function SearchBox<T extends { name: string }>({ placeholder, items, onSelect, labelFor }: { placeholder: string; items: T[]; onSelect: (item: T) => void; labelFor?: (item: T) => string }) {
  const [query, setQuery] = useState('');
  const matches = query.length >= 2 ? items.filter((item) => (labelFor?.(item) ?? item.name).toLowerCase().includes(query.toLowerCase())).slice(0, 20) : [];
  return <div className="searchbox"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} />{matches.length ? <div className="results">{matches.map((item, index) => <button key={`${labelFor?.(item) ?? item.name}-${index}`} onClick={() => { onSelect(item); setQuery(''); }}>{labelFor?.(item) ?? item.name}</button>)}</div> : null}</div>;
}

function RiskBadge({ value, level }: { value?: number; level?: RiskLevel }) { return <span className="risk-badge" style={{ borderColor: colorByLevel[level ?? 'Unknown'], color: colorByLevel[level ?? 'Unknown'] }}>{level ?? 'Unknown'} {value ?? '--'}/100</span>; }

function SourceLine({ score }: { score?: RiskScore }) { return <div className="source-line"><span>{score?.sources.join(', ') || 'Provider not connected'}</span><span>{sourceStatusLabel(score?.sourceStatus)}</span><span>{score?.confidence ?? 'Low'} confidence</span><span>{score?.lastUpdated ? new Date(score.lastUpdated).toLocaleString() : 'Not updated'}</span></div>; }

function SectionBlock({ id, title, score, summary, meaning }: { id?: string; title: string; score?: RiskScore; summary?: string; meaning?: string }) {
  return <div className="guide-block" id={id}><div className="section-head"><h3>{title}</h3><RiskBadge value={score?.value} level={score?.level} /></div><p>{summary || score?.meaning || 'Limited verified data available.'}</p><div className="means"><strong>What this means for travel</strong><span>{meaning || travelMeaning(score)}</span></div><SourceLine score={score} /></div>;
}

function IntelligencePanel({ country, city, rawName, onCity }: { country: CountryProfile | null; city: CityProfile | null; rawName: string; onCity: (city: CityProfile) => void }) {
  const [tab, setTab] = useState('Summary');
  const targetScore = scoreFor(city ?? country);
  if (!country && !city && !rawName) return null;
  if (!country && !city) return <section className="card intelligence-panel"><div className="card-header"><h2>{rawName}</h2><RiskBadge /></div><div className="list"><p className="muted">Limited verified data available.</p></div></section>;

  const countryAlerts = country ? alerts.filter((alert) => alert.country === country.name) : [];
  const cityEvents = country ? cities.filter((item) => item.countryIso2 === country.iso2 && (scoreFor(item)?.value ?? 0) >= 45) : [];
  const support = (targetScore?.value ?? 0) >= 75 ? ['Secure transport', 'Close protection', 'Remote medic', 'Medical evacuation planning'] : (targetScore?.value ?? 0) >= 50 ? ['Vetted driver', 'Secure transport', 'Enhanced awareness'] : ['Enhanced awareness', 'Standard journey monitoring'];
  const tabs = ['Summary', 'Risks', 'Health', 'Movement', 'Advisories', 'Sources'];
  const riskByCategory = (category: string) => country?.risk.find((item) => item.category === category);
  const riskCards = country?.risk.filter((item) => item.category !== 'overall') ?? [];

  return <section className="card intelligence-panel elite-guide" data-testid="country-breakdown"><div className="card-header"><div><div className="eyebrow">Atlas Insight country guide</div><h2>{city ? `${city.name}, ${country?.name}` : `${country?.name} - ${targetScore?.level ?? 'Unknown'} Risk`}</h2></div><div className="guide-actions"><button className="secondary"><Star size={15} /> Add to monitoring</button><button className="secondary"><Bell size={15} /> Request updates</button><button className="secondary"><Mail size={15} /> Request email alerts</button></div></div>
    <div className="intel-strip"><div><span>Overall risk</span><RiskBadge value={targetScore?.value} level={targetScore?.level} /></div><div><span>Current advisory</span><strong>{advisoryFor(country)}</strong></div><div><span>Last updated</span><strong>{targetScore?.lastUpdated ? new Date(targetScore.lastUpdated).toLocaleString() : 'Unknown'}</strong></div><div><span>Confidence</span><strong>{targetScore?.confidence ?? 'Low'}</strong></div><div><span>Key issue</span><strong>{keyIssue(country)}</strong></div><div><span>Source status</span><strong>{sourceStatusLabel(targetScore?.sourceStatus)}</strong></div></div>
    <div className="risk-card-grid">{riskCards.map((item) => <button key={item.category} className="risk-card" onClick={() => setTab(['health', 'medical', 'naturalDisaster'].includes(item.category) ? 'Health' : ['transport', 'infrastructure', 'legalCultural', 'travelDisruption'].includes(item.category) ? 'Movement' : 'Risks')}><span>{categoryLabel(item.category)}</span><strong style={{ color: colorByLevel[item.level] }}>{item.level}</strong><small>{item.value}/100</small></button>)}</div>
    <div className="tab-row">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>
    <div className="guide-grid">
      {tab === 'Summary' ? <><div className="guide-block wide"><div className="section-head"><h3>Executive summary</h3><RiskBadge value={targetScore?.value} level={targetScore?.level} /></div><p>{city ? city.overview : country?.securityOverview}</p><div className="means"><strong>What this means for travel</strong><span>{travelMeaning(targetScore)}</span></div><SourceLine score={targetScore} /></div><SectionBlock title="Current advisory position" score={targetScore} summary={advisoryFor(country)} meaning="Review official advisory status before booking and again within 24 hours of departure." /><SectionBlock title="Overall risk rating" score={targetScore} summary={targetScore?.meaning} /><div className="guide-block wide"><h3>Baseline</h3><p>Capital: {country?.capital}. Region: {country?.region}. Population: {country?.population}. Government: {country?.governmentType}. Languages: {country?.languages.join(', ')}. Currency: {country?.currency}. Time zone: {country?.timeZones.join(', ')}.</p><SourceLine score={targetScore} /></div><div className="guide-block"><h3>Recommended precautions</h3><ul>{support.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="guide-block"><h3>Operational support recommendation</h3><p>{support.join(', ')}.</p><SourceLine score={targetScore} /></div></> : null}
      {tab === 'Risks' ? <><SectionBlock title="Security" score={riskByCategory('security')} summary={country?.securityOverview} /><SectionBlock title="Crime" score={riskByCategory('crime')} summary={country?.crimeOverview} /><SectionBlock title="Political stability" score={riskByCategory('political')} summary={country?.politicalStability} /><SectionBlock title="Civil unrest/protest risk" score={riskByCategory('political')} summary={country?.protestCivilUnrestRisk} /><SectionBlock title="Terrorism/conflict" score={riskByCategory('terrorismConflict')} summary={country?.terrorismConflictOverview} /><SectionBlock title="Kidnap/extortion" score={riskByCategory('kidnapExtortion')} summary={country?.kidnapExtortionRisk} /></> : null}
      {tab === 'Health' ? <><SectionBlock title="Health and disease risk" score={riskByCategory('health')} summary={country?.healthRisks} /><SectionBlock title="Food/water hygiene" score={riskByCategory('health')} summary={country?.hygieneWaterFoodSafety} /><SectionBlock title="Medical capability" score={riskByCategory('medical')} summary={country?.medicalCapability} /><SectionBlock title="Emergency services capability" score={riskByCategory('medical')} summary={country?.emergencyServicesCapability} /><SectionBlock title="Natural hazards" score={riskByCategory('naturalDisaster')} summary={country?.naturalHazards} /></> : null}
      {tab === 'Movement' ? <><SectionBlock title="Transport/infrastructure" score={riskByCategory('transport')} summary={country?.transportInfrastructureRisk} /><SectionBlock title="Airport/travel disruption" score={riskByCategory('travelDisruption')} summary={country?.airportTravelDisruptionRisk} /><SectionBlock title="Local laws/cultural considerations" score={riskByCategory('legalCultural')} summary={country?.localLawsCulture} /><div className="guide-block"><h3>Areas to avoid</h3><p>{country?.areasToAvoid.join(', ')}</p><SourceLine score={targetScore} /></div><div className="guide-block"><h3>Key city-level events</h3>{cityEvents.length ? cityEvents.map((item) => { const cityScore = scoreFor(item); return <button className="city-event" key={item.id} onClick={() => onCity(item)}><strong>{item.name}</strong><RiskBadge value={cityScore?.value} level={cityScore?.level} /><span>{item.overview}</span><small>{sourceStatusLabel(cityScore?.sourceStatus)} - {cityScore?.lastUpdated ? new Date(cityScore.lastUpdated).toLocaleString() : 'Unknown'}</small></button>; }) : <p className="muted">Limited verified city-level event data available.</p>}</div></> : null}
      {tab === 'Advisories' ? <><div className="guide-block wide"><h3>Current advisories</h3>{countryAlerts.length ? countryAlerts.map((alert) => <button className="feed-click" key={alert.id}><strong>{alert.severity}: {alert.title}</strong><span>{alert.summary}</span><small>{alert.source} - Demo fallback - {new Date(alert.timestamp).toLocaleString()}</small></button>) : <p className="muted">No current live advisories connected for this profile.</p>}</div><div className="guide-block wide"><h3>Recommended precautions</h3><ul>{support.map((item) => <li key={item}>{item}</li>)}</ul></div></> : null}
      {tab === 'Sources' ? <><div className="guide-block wide"><h3>Sources and confidence</h3><p>Atlas Insight distinguishes live provider, public baseline, manual admin input, demo fallback and AI-assisted summaries. Current risk/advisory/event intelligence remains demo-labelled until live providers are configured and ingested.</p><SourceLine score={targetScore} /></div><div className="guide-block wide"><h3>Risk score breakdown</h3>{country?.risk.filter((item) => item.category !== 'overall').map((item) => <div className="risk-row compact" key={item.category}><span>{categoryLabel(item.category)}</span><strong style={{ color: colorByLevel[item.level] }}>{item.value}</strong><div className="bar"><span style={{ width: `${item.value}%`, background: colorByLevel[item.level] }} /></div></div>)}</div></> : null}
    </div></section>;
}

function FeedPanel({ title, items, onSelect }: { title: string; items: Alert[]; onSelect: (alert: Alert) => void }) { return <div className="card feed-card"><div className="card-header"><h3>{title}</h3></div><div className="scroll-feed">{items.length ? items.map((alert) => <button className="feed-click" key={`${title}-${alert.id}`} onClick={() => onSelect(alert)}><strong>{alert.severity}: {alert.title}</strong><span>{alert.city ? `${alert.city}, ` : ''}{alert.country} - {new Date(alert.timestamp).toLocaleString()}</span><small>{alert.source} - demo fallback</small></button>) : <p className="muted">No current matching updates.</p>}</div></div>; }

function Dashboard({ countries, setView, openAlert }: { countries: CountryProfile[]; setView: (view: ViewName) => void; openAlert: (alert: Alert) => void }) {
  const ranked = [...fallbackCountries].sort((a, b) => (scoreFor(b)?.value ?? 0) - (scoreFor(a)?.value ?? 0));
  const incidentCounts = { Security: 2, Health: 1, Natural: 1, Political: 1, Other: 1 };
  const feedFor = (title: string) => title === 'Critical Security Alerts' ? alerts.filter((a) => ['High', 'Critical'].includes(a.severity)) : title.includes('Political') ? alerts.filter((a) => a.category.includes('Political')) : title.includes('Terrorism') ? alerts.filter((a) => ['Conflict', 'Security'].includes(a.category)) : title.includes('Health') ? alerts.filter((a) => a.category.includes('Health')) : title.includes('Natural') ? alerts.filter((a) => a.category.includes('Natural')) : title.includes('Travel') || title.includes('Aviation') ? alerts.filter((a) => a.category.includes('Travel')) : alerts;
  return <><section className="dashboard-grid"><div className="card map-card"><div className="card-header"><div><h2>Executive Risk Map</h2><p className="muted">2D overview. High and critical city alerts only.</p></div><button className="secondary" onClick={() => setView('Risk Map')}>Open full map</button></div><div className="map-wrap executive-map"><WorldMap mode="dashboard" countries={countries} onAlertClick={openAlert} /></div></div><div className="side-stack"><div className="card metric"><h3>Current Alerts</h3><div><span className="metric-number red">{highCriticalAlerts().length}</span> <span className="muted">High/Critical</span></div></div><div className="card metric"><h3>Incidents Today</h3><div><span className="metric-number">{alerts.length + 23}</span> <span className="muted">Worldwide</span></div></div><div className="card metric"><h3>Travel Advisories</h3><div><span className="metric-number blue">8</span> <span className="muted">Updated today</span></div></div></div></section><section className="lower-grid"><div className="card"><div className="card-header"><h2>Risk by Country</h2></div><div className="list">{ranked.map((country) => { const value = scoreFor(country)?.value ?? 0; const level = scoreFor(country)?.level ?? 'Low'; return <div className="risk-row" key={country.iso2}><span>{country.name}</span><strong style={{ color: colorByLevel[level] }}>{level}</strong><div className="bar"><span style={{ width: `${value}%`, background: colorByLevel[level] }} /></div></div>; })}</div></div><div className="card"><div className="card-header"><h2>Incident Categories</h2></div><div className="list">{Object.entries(incidentCounts).map(([name, value]) => <div className="risk-row" key={name}><span>{name}</span><strong>{value}</strong><div className="bar"><span style={{ width: `${value * 18}%`, background: name === 'Security' ? '#5ab2d8' : name === 'Health' ? '#f97316' : name === 'Natural' ? '#f6c343' : '#63b86f' }} /></div></div>)}</div></div><div className="card"><div className="card-header"><h2>Live Travel Intelligence</h2></div><div className="list">{alerts.map((alert) => <button className="feed-click" key={alert.id} onClick={() => openAlert(alert)}><strong>{alert.title}</strong><span>{alert.country}{alert.city ? `, ${alert.city}` : ''} - {alert.severity} - {alert.source}</span></button>)}</div></div></section><section className="feed-grid">{categoryFeeds.map((title) => <FeedPanel key={title} title={title} items={feedFor(title)} onSelect={openAlert} />)}</section></>;
}

function RiskMapView({ countries, selectedCountry, selectedCity, setSelectedCountry, setSelectedCity, rawName, setRawName }: { countries: CountryProfile[]; selectedCountry: CountryProfile | null; selectedCity: CityProfile | null; setSelectedCountry: (country: CountryProfile | null) => void; setSelectedCity: (city: CityProfile | null) => void; rawName: string; setRawName: (value: string) => void }) {
  const openCity = (city: CityProfile) => { setSelectedCity(city); setSelectedCountry(countryForCity(city, countries)); setRawName(city.name); };
  return <><section className="card map-card risk-map-card"><div className="card-header"><div><h2>Full 2D Risk Map</h2><p className="muted">Hover for a temporary snapshot. Click a country or city to open the full brief below.</p></div><div className="legend"><span><i className="dot" style={{ background: colorByLevel.Low }} />Low</span><span><i className="dot" style={{ background: colorByLevel.Moderate }} />Moderate</span><span><i className="dot" style={{ background: colorByLevel.High }} />High</span><span><i className="dot" style={{ background: colorByLevel.Critical }} />Critical</span></div></div><div className="search-row"><SearchBox placeholder="Search countries" items={countries} onSelect={(country) => { setSelectedCountry(country); setSelectedCity(null); setRawName(country.name); }} /><SearchBox placeholder="Search cities globally" items={cities} labelFor={(city) => `${city.name}, ${countryForCity(city, countries)?.name}`} onSelect={openCity} /></div><div className="map-wrap full-map"><WorldMap mode="risk" countries={countries} selectedCity={selectedCity} onCountry={(country, name) => { setSelectedCountry(country); setSelectedCity(null); setRawName(name); }} onCity={openCity} /></div></section><IntelligencePanel country={selectedCountry} city={selectedCity} rawName={rawName} onCity={openCity} /></>;
}

function AccountPanel({ paid, setPaid }: { paid: boolean; setPaid: (paid: boolean) => void }) { return <div className="card"><div className="card-header"><div><h2>Account Access</h2><p className="muted">Demo login scaffolding for free/client access. Production uses real auth and Stripe.</p></div><span className="pill"><UserRound size={16} /> {paid ? 'Client' : 'Free'}</span></div><div className="form-grid"><div className="field"><label>Email</label><input defaultValue="client@atlasinsight.example" /></div><div className="field"><label>Password</label><input type="password" defaultValue="atlas-demo" /></div><button className="primary" onClick={() => setPaid(true)}>Sign up / log in as client</button><button className="secondary" onClick={() => setPaid(false)}>Use free tier</button></div></div>; }

function TripFlow({ paid, latestReport, setLatestReport, onTripChange }: { paid: boolean; latestReport: TripReport | null; setLatestReport: (report: TripReport | null) => void; onTripChange: (trip: Trip | null) => void }) {
  const [step, setStep] = useState(0);
  const [trip, setTrip] = useState<Trip | null>(null);
  const [documents, setDocuments] = useState<TripDocument[]>([]);
  const [selectedDocument, setSelectedDocument] = useState<TripDocument | null>(null);
  const [message, setMessage] = useState('');
  const [aiStatus, setAiStatus] = useState<AiStatus | null>(null);
  const [aiMessage, setAiMessage] = useState('');
  const [form, setForm] = useState({ name: 'Nairobi executive visit', countryIso2: 'KE', country: 'Kenya', city: 'Nairobi', arrivalDate: '2026-06-10', departureDate: '2026-06-14', nationality: 'British', gender: 'Not specified', travelStyle: 'executive', medicalConsiderations: 'None declared', riskTolerance: 'medium', purpose: 'Board meetings', accommodation: 'Secure business hotel near meeting site', flightDetails: 'International arrival and departure via NBO', internalMovements: 'Airport transfer, hotel to offices, client dinner route', meetingsEvents: 'Board meeting and investor dinner' });
  useEffect(() => { fetch('/api/ai/status').then((response) => response.json()).then(setAiStatus).catch(() => setAiStatus({ configured: false, provider: 'Not configured', model: 'Not configured', status: 'AI extraction unavailable - manual entry required' })); }, []);
  const missing = missingDocuments(documents);
  const missingFields = Object.entries({ country: form.country, city: form.city, arrivalDate: form.arrivalDate, departureDate: form.departureDate, accommodation: form.accommodation, flightDetails: form.flightDetails, internalMovements: form.internalMovements, meetingsEvents: form.meetingsEvents }).filter(([, value]) => !value).map(([key]) => key);
  const tripRiskScore = scoreFor(fallbackCountries.find((country) => country.iso2 === form.countryIso2))?.value ?? 0;
  const setField = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function createTrip() { setMessage(''); const response = await fetch('/api/trips', { method: 'POST', headers: { 'content-type': 'application/json', 'x-demo-paid': paid ? 'true' : 'false' }, body: JSON.stringify({ name: form.name, traveller: { nationality: form.nationality, gender: form.gender, travelStyle: form.travelStyle, highProfile: form.travelStyle === 'executive', medicalConsiderations: form.medicalConsiderations, riskTolerance: form.riskTolerance, purpose: form.purpose, childrenTravelling: false, hostileEnvironmentSupport: tripRiskScore > 60 }, locations: [{ countryIso2: form.countryIso2, country: form.country, city: form.city, arrivalDate: form.arrivalDate, departureDate: form.departureDate }], accommodation: form.accommodation, flightDetails: form.flightDetails, internalMovements: form.internalMovements, meetingsEvents: form.meetingsEvents }) }); const json = await response.json(); if (!response.ok) setMessage(json.error ?? 'Unable to create trip'); else { setTrip(json.data); onTripChange(json.data); setMessage('Trip created. Continue to documents and assessment.'); setStep(5); } }
  async function uploadDoc(type: string) { if (!trip) return; setAiMessage(''); const response = await fetch(`/api/trips/${trip.id}/documents`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-demo-paid': paid ? 'true' : 'false' }, body: JSON.stringify({ type, fileName: `${type.toLowerCase().replaceAll(' ', '-')}.pdf`, mimeType: 'application/pdf', size: 120000 }) }); const json = await response.json(); if (response.ok) { setDocuments((current) => [...current, json.data]); const ai = await fetch('/api/ai/extract-document', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ fileName: json.data.fileName }) }).then((item) => item.json()).catch(() => null); setAiMessage(ai?.text ?? 'AI extraction unavailable — manual entry required.'); } }
  async function viewDoc(doc: TripDocument) { if (!trip) return; const response = await fetch(`/api/trips/${trip.id}/documents/${doc.id}`, { headers: { 'x-demo-paid': paid ? 'true' : 'false' } }); const json = await response.json(); if (response.ok) setSelectedDocument(json.data); }
  async function deleteDoc(doc: TripDocument) { if (!trip) return; const response = await fetch(`/api/trips/${trip.id}/documents/${doc.id}`, { method: 'DELETE', headers: { 'x-demo-paid': paid ? 'true' : 'false' } }); if (response.ok) setDocuments((current) => current.filter((item) => item.id !== doc.id)); }
  async function generateReport() { if (!trip) { setMessage('Create a trip before generating a report.'); return; } if (missingFields.length) { setMessage(`Complete missing fields before assessment: ${missingFields.join(', ')}`); return; } const response = await fetch('/api/reports/generate', { method: 'POST', headers: { 'content-type': 'application/json', 'x-demo-paid': paid ? 'true' : 'false' }, body: JSON.stringify({ tripId: trip.id }) }); const json = await response.json(); if (response.ok) { setLatestReport(json.data); setStep(7); setMessage('Report saved and ready to download.'); } else setMessage(json.error ?? 'Report generation failed.'); }
  return <section className="card trip-builder"><div className="card-header"><div><div className="eyebrow">Guided client workflow</div><h2>Trip Builder</h2></div>{paid ? <span className="pill"><Shield size={16} /> Client access</span> : <span className="pill"><AlertTriangle size={16} /> Upgrade required</span>}</div><div className="step-rail">{tripSteps.map((item, index) => <button key={item} className={step === index ? 'active' : index < step ? 'done' : ''} onClick={() => setStep(index)}><span>{index < step ? <CheckCircle2 size={14} /> : index + 1}</span>{item}</button>)}</div><div className="builder-body">
    {step === 0 ? <BuilderCard title="1. Destination" note="Choose the country and city that will drive the risk assessment."><div className="form-grid"><Field label="Trip name" value={form.name} onChange={(value) => setField('name', value)} /><Field label="Destination country" value={form.country} onChange={(value) => setField('country', value)} /><Field label="Country ISO2" value={form.countryIso2} onChange={(value) => setField('countryIso2', value.toUpperCase())} /><Field label="Destination city" value={form.city} onChange={(value) => setField('city', value)} /></div></BuilderCard> : null}
    {step === 1 ? <BuilderCard title="2. Dates" note="Capture the travel window so alerts can be linked to the itinerary."><div className="form-grid"><Field label="Arrival date" value={form.arrivalDate} onChange={(value) => setField('arrivalDate', value)} /><Field label="Departure date" value={form.departureDate} onChange={(value) => setField('departureDate', value)} /></div></BuilderCard> : null}
    {step === 2 ? <BuilderCard title="3. Traveller profile" note="Risk recommendations change for executives, families, solo travellers and medical factors."><div className="form-grid"><Field label="Nationality" value={form.nationality} onChange={(value) => setField('nationality', value)} /><Field label="Gender" value={form.gender} onChange={(value) => setField('gender', value)} /><Field label="Traveller type" value={form.travelStyle} onChange={(value) => setField('travelStyle', value)} /><Field label="Risk tolerance" value={form.riskTolerance} onChange={(value) => setField('riskTolerance', value)} /><Field label="Medical factors" value={form.medicalConsiderations} onChange={(value) => setField('medicalConsiderations', value)} /><Field label="Purpose" value={form.purpose} onChange={(value) => setField('purpose', value)} /></div></BuilderCard> : null}
    {step === 3 ? <BuilderCard title="4. Accommodation" note="Hotel location and access control influence movement and support recommendations."><div className="form-grid"><Field label="Accommodation" value={form.accommodation} onChange={(value) => setField('accommodation', value)} full /></div></BuilderCard> : null}
    {step === 4 ? <BuilderCard title="5. Flights / routes / meetings" note="Add the movement plan. This is used in the tailored report."><div className="form-grid"><Field label="Flights" value={form.flightDetails} onChange={(value) => setField('flightDetails', value)} /><Field label="Internal movements" value={form.internalMovements} onChange={(value) => setField('internalMovements', value)} /><Field label="Meetings / events" value={form.meetingsEvents} onChange={(value) => setField('meetingsEvents', value)} full /></div><button className="primary" onClick={createTrip}>Create Trip</button>{message ? <p className="muted">{message}</p> : null}</BuilderCard> : null}
    {step === 5 ? <BuilderCard title="6. Documents" note={trip ? 'Upload document metadata now or later. File bytes are S3-ready through signed URL APIs.' : 'Create the trip before adding documents.'}>{trip ? <><div className="ai-panel"><Sparkles size={16} /><div><strong>AI extraction</strong><p>{aiStatus?.configured ? `AI provider configured: ${aiStatus.provider} / ${aiStatus.model}. Extracted fields are used only when confidence is high.` : 'AI extraction unavailable — manual entry required.'}</p></div></div><div className="document-actions">{documentTypes.map((type) => <button className="secondary" key={type} onClick={() => uploadDoc(type)}><Upload size={15} /> {type}</button>)}</div>{aiMessage ? <p className="muted">{aiMessage}</p> : null}<p className="muted">Missing documents: {missing.join(', ') || 'None'}</p>{documents.length ? <table className="table"><tbody>{documents.map((doc) => <tr key={doc.id}><td>{doc.type}</td><td>{doc.fileName}</td><td>{doc.storageKey}</td><td><button className="secondary" onClick={() => viewDoc(doc)}>View</button></td><td><button className="icon-button" onClick={() => deleteDoc(doc)} title="Delete document"><Trash2 size={16} /></button></td></tr>)}</tbody></table> : <p className="empty-state">No documents added yet.</p>}{selectedDocument ? <p className="muted">Viewing metadata: {selectedDocument.fileName} stored at {selectedDocument.storageKey}</p> : null}</> : <p className="empty-state">Complete destination, traveller and route details first.</p>}</BuilderCard> : null}
    {step === 6 ? <BuilderCard title="7. Risk assessment" note="Run the Atlas Insight rules engine against itinerary, traveller profile, documents and latest demo/provider intelligence.">{trip ? <><div className="assessment-grid"><div><span>Destination</span><strong>{trip.locations[0].city}, {trip.locations[0].country}</strong></div><div><span>Risk score</span><strong>{tripRiskScore}/100</strong></div><div><span>Missing fields</span><strong>{missingFields.join(', ') || 'None'}</strong></div><div><span>Missing documents</span><strong>{missing.join(', ') || 'None'}</strong></div></div><button className="primary" onClick={generateReport}>Run Assessment and Generate Report</button>{message ? <p className="muted">{message}</p> : null}</> : <p className="empty-state">Create a trip before running assessment.</p>}</BuilderCard> : null}
    {step === 7 ? <BuilderCard title="8. Report" note="Save, review and download the tailored travel risk report.">{latestReport ? <ReportView report={latestReport} /> : <p className="empty-state">No report generated yet.</p>}</BuilderCard> : null}
  </div><div className="builder-footer"><button className="secondary" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))}>Back</button><button className="primary" disabled={step === tripSteps.length - 1} onClick={() => setStep(Math.min(tripSteps.length - 1, step + 1))}>Continue</button></div></section>;
}

function Field({ label, value, onChange, full }: { label: string; value: string; onChange: (value: string) => void; full?: boolean }) { return <div className={`field ${full ? 'full' : ''}`}><label>{label}</label><input value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function BuilderCard({ title, note, children }: { title: string; note: string; children: React.ReactNode }) { return <div className="builder-card"><h3>{title}</h3><p className="muted">{note}</p>{children}</div>; }
function ReportView({ report }: { report: TripReport }) { return <div><div className="card-header report-head"><h3>{report.title}</h3><a className="secondary" href={`/api/reports/${report.id}/download`}>Download report</a></div><div className="report">{report.markdown}</div></div>; }
function SimpleListView({ title, children }: { title: string; children: React.ReactNode }) { return <section className="card"><div className="card-header"><h2>{title}</h2></div><div className="list">{children}</div></section>; }

function SummaryModal({ target, onClose, openBrief }: { target: BriefTarget; onClose: () => void; openBrief: () => void }) {
  if (!target) return null;
  const profile = target.type === 'country' ? target.country : target.city;
  const country = target.type === 'country' ? target.country : target.country;
  const score = scoreFor(profile);
  return <div className="modal-backdrop"><div className="summary-modal"><button className="icon-button modal-close" onClick={onClose} title="Close"><X size={16} /></button><div className="eyebrow">Atlas Insight brief</div><h2>{target.type === 'country' ? target.country.name : `${target.city.name}, ${target.country?.name}`}</h2><RiskBadge value={score?.value} level={score?.level} /><p>{target.type === 'country' ? target.country.securityOverview : target.city.overview}</p><div className="source-line"><span>{advisoryFor(country)}</span><span>{sourceStatusLabel(score?.sourceStatus)}</span><span>{score?.confidence ?? 'Low'} confidence</span></div><button className="primary" onClick={openBrief}>Open full Risk Map brief</button></div></div>;
}

function CountryCard({ country, pinned, togglePin, open }: { country: CountryProfile; pinned: boolean; togglePin: () => void; open: () => void }) { const score = scoreFor(country); return <article className="intel-card country-card" onClick={open}><button className={`pin ${pinned ? 'active' : ''}`} onClick={(event) => { event.stopPropagation(); togglePin(); }} title="Pin country"><Star size={15} /></button><div className="country-image"><span>{country.iso2}</span></div><div><h3>{country.name}</h3><p>{country.region}</p></div><RiskBadge value={score?.value} level={score?.level} /><small>{advisoryFor(country)}</small><small>Updated {score?.lastUpdated ? new Date(score.lastUpdated).toLocaleDateString() : 'Unknown'}</small><button className="secondary" onClick={(event) => event.stopPropagation()}><Mail size={14} /> Request email updates for this country</button></article>; }

function CountriesView({ countries, pinned, setPinned, openBrief }: { countries: CountryProfile[]; pinned: string[]; setPinned: (items: string[]) => void; openBrief: (country: CountryProfile) => void }) {
  const [target, setTarget] = useState<BriefTarget>(null);
  const monitored = countries.filter((country) => pinned.includes(country.iso2));
  const rest = countries.filter((country) => !pinned.includes(country.iso2)).slice(0, 40);
  const toggle = (iso: string) => setPinned(pinned.includes(iso) ? pinned.filter((item) => item !== iso) : [...pinned, iso]);
  return <><section className="card page-card"><div className="card-header"><div><h2>Country Intelligence</h2><p className="muted">Search public baseline and Atlas Insight fallback profiles. Risk intelligence is source-labelled.</p></div></div><div className="search-row single"><SearchBox placeholder="Search countries" items={countries} onSelect={(country) => setTarget({ type: 'country', country })} /></div>{monitored.length ? <><div className="section-title">Monitored Countries</div><div className="card-grid">{monitored.map((country) => <CountryCard key={country.iso2} country={country} pinned togglePin={() => toggle(country.iso2)} open={() => setTarget({ type: 'country', country })} />)}</div></> : null}<div className="section-title">All Countries</div><div className="card-grid">{rest.map((country) => <CountryCard key={country.iso2} country={country} pinned={false} togglePin={() => toggle(country.iso2)} open={() => setTarget({ type: 'country', country })} />)}</div></section><SummaryModal target={target} onClose={() => setTarget(null)} openBrief={() => { if (target?.type === 'country') openBrief(target.country); setTarget(null); }} /></>;
}

function CityCard({ city, country, pinned, togglePin, open }: { city: CityProfile; country: CountryProfile | null; pinned: boolean; togglePin: () => void; open: () => void }) { const score = scoreFor(city); return <article className="intel-card city-card" onClick={open}><button className={`pin ${pinned ? 'active' : ''}`} onClick={(event) => { event.stopPropagation(); togglePin(); }} title="Pin city"><Star size={15} /></button><h3>{city.name}</h3><p>{country?.name ?? city.countryIso2}</p><RiskBadge value={score?.value} level={score?.level} /><small>{score?.value && score.value < 25 ? 'Key strength: stable operating environment' : `Key issue: ${city.overview}`}</small><small>Updated {score?.lastUpdated ? new Date(score.lastUpdated).toLocaleDateString() : 'Unknown'}</small><button className="secondary" onClick={(event) => event.stopPropagation()}><Mail size={14} /> Request email updates for this city</button></article>; }

function CitiesView({ countries, pinned, setPinned, openBrief }: { countries: CountryProfile[]; pinned: string[]; setPinned: (items: string[]) => void; openBrief: (city: CityProfile) => void }) {
  const [target, setTarget] = useState<BriefTarget>(null);
  const monitored = cities.filter((city) => pinned.includes(city.id));
  const safest = [...cities].sort((a, b) => (scoreFor(a)?.value ?? 0) - (scoreFor(b)?.value ?? 0)).slice(0, 5);
  const riskiest = [...cities].sort((a, b) => (scoreFor(b)?.value ?? 0) - (scoreFor(a)?.value ?? 0)).slice(0, 5);
  const toggle = (id: string) => setPinned(pinned.includes(id) ? pinned.filter((item) => item !== id) : [...pinned, id]);
  const card = (city: CityProfile) => <CityCard key={city.id} city={city} country={countryForCity(city, countries)} pinned={pinned.includes(city.id)} togglePin={() => toggle(city.id)} open={() => setTarget({ type: 'city', city, country: countryForCity(city, countries) })} />;
  return <><section className="card page-card"><div className="card-header"><div><h2>City Intelligence</h2><p className="muted">Search all available city profiles and monitor the locations that matter to your trips.</p></div></div><div className="search-row single"><SearchBox placeholder="Search cities" items={cities} labelFor={(city) => `${city.name}, ${countryForCity(city, countries)?.name}`} onSelect={(city) => setTarget({ type: 'city', city, country: countryForCity(city, countries) })} /></div>{monitored.length ? <><div className="section-title">Monitored Cities</div><div className="card-grid compact-grid">{monitored.map(card)}</div></> : null}<div className="two-columns"><div><div className="section-title">Top 5 Safest Cities</div><div className="card-grid one-column">{safest.map(card)}</div></div><div><div className="section-title">Top 5 Highest Risk Cities</div><div className="card-grid one-column">{riskiest.map(card)}</div></div></div></section><SummaryModal target={target} onClose={() => setTarget(null)} openBrief={() => { if (target?.type === 'city') openBrief(target.city); setTarget(null); }} /></>;
}

function TravelFeedView({ trip, openAlert, openTrip }: { trip: Trip | null; openAlert: (alert: Alert) => void; openTrip: () => void }) { const tripAlerts = trip ? alerts.filter((alert) => alert.country === trip.locations[0]?.country || alert.city === trip.locations[0]?.city) : []; return <section className="feed-layout"><div className="card"><div className="card-header"><h2>Global Updates</h2></div><div className="list">{alerts.map((alert) => <button className="feed-click" key={alert.id} onClick={() => openAlert(alert)}><strong>{alert.severity}: {alert.title}</strong><span>{alert.city ? `${alert.city}, ` : ''}{alert.country} - {new Date(alert.timestamp).toLocaleString()}</span><small>{alert.source} - Demo fallback</small></button>)}</div></div><div className="card"><div className="card-header"><h2>My Trip Updates</h2></div><div className="list">{trip ? <><button className="trip-strip" onClick={openTrip}><Plane size={16} /><span>{trip.name}</span><small>{trip.locations[0]?.city}, {trip.locations[0]?.country}</small></button>{tripAlerts.length ? tripAlerts.map((alert) => <button className="feed-click" key={`trip-${alert.id}`} onClick={() => openAlert(alert)}><strong>{alert.severity}: {alert.title}</strong><span>{alert.summary}</span><small>Linked to {trip.name} - {sourceStatusLabel('demo')}</small></button>) : <p className="empty-state">No trip-specific alerts for this itinerary yet.</p>}</> : <p className="empty-state">No trips planned. Create an itinerary to receive trip-linked travel intelligence.</p>}</div></div></section>; }

function SupportView({ trip }: { trip: Trip | null }) { const [sent, setSent] = useState(''); const types = ['Vetted driver', 'Secure transport', 'Close protection', 'Remote medic', 'On-ground medic', 'Medical evacuation planning', 'Crisis response support']; return <section className="support-grid"><div className="card"><div className="card-header"><h2>Emergency Contact Guidance</h2></div><div className="list"><p>Save local emergency numbers, embassy/consulate contacts, insurer assistance, hotel security, and employer duty officer details offline before travel.</p><p className="muted">Atlas Insight support desk placeholder: support@atlasinsight.example / +44 0000 000000. Replace with operational contact details before production launch.</p></div></div><div className="card"><div className="card-header"><h2>Request Operational Support</h2></div><div className="list"><p className="muted">{trip ? `Linking request to ${trip.name}.` : 'No trips exist yet. Submit a general support enquiry.'}</p><div className="support-types">{types.map((type) => <button className="secondary" key={type} onClick={() => setSent(`${type} request prepared${trip ? ` for ${trip.name}` : ''}.`)}>{type}</button>)}</div><button className="primary" onClick={() => setSent(trip ? `Operational support request linked to ${trip.name}.` : 'General operational support enquiry prepared.')}>Request Operational Support</button>{sent ? <p className="muted">{sent}</p> : null}</div></div></section>; }

function SettingsView({ paid, setPaid }: { paid: boolean; setPaid: (paid: boolean) => void }) {
  const [providers, setProviders] = useState<ProviderStatus[]>([]);
  useEffect(() => { fetch('/api/admin/provider-status').then((response) => response.json()).then((json) => setProviders(json.providers ?? [])).catch(() => setProviders([])); }, []);
  return <><SimpleListView title="Settings"><AccountPanel paid={paid} setPaid={setPaid} /><p className="muted">Provider status, Neon connection health, S3 storage, Stripe, AI support, and admin controls are shown below.</p></SimpleListView><section className="card"><div className="card-header"><h2>Provider Status</h2><span className="pill">Connected / Missing key / Demo fallback active</span></div><div className="provider-grid">{providers.map((provider) => <div className="provider-card" key={provider.key}><strong>{provider.name}</strong><span>{provider.category}</span><b className={provider.status.includes('Live') || provider.status.includes('Public') ? 'ok' : 'warn'}>{provider.status}</b><small>{provider.notes}</small></div>)}</div></section></>;
}

export default function HomePage() {
  const countryCatalog = useCountryCatalog();
  const [active, setActive] = useState<ViewName>('Dashboard');
  const [paid, setPaid] = useState(false);
  const [latestReport, setLatestReport] = useState<TripReport | null>(null);
  const [plannedTrip, setPlannedTrip] = useState<Trip | null>(null);
  const [selectedCountry, setSelectedCountry] = useState<CountryProfile | null>(fallbackCountries[2]);
  const [selectedCity, setSelectedCity] = useState<CityProfile | null>(null);
  const [rawName, setRawName] = useState('Kenya');
  const [pinnedCountries, setPinnedCountries] = useState<string[]>([]);
  const [pinnedCities, setPinnedCities] = useState<string[]>([]);
  function openAlert(alert: Alert) { const profiles = profileForAlert(alert, countryCatalog); setSelectedCountry(profiles.country); setSelectedCity(profiles.city); setRawName(alert.city ?? alert.country); setActive('Risk Map'); }
  function openCountryBrief(country: CountryProfile) { setSelectedCountry(country); setSelectedCity(null); setRawName(country.name); setActive('Risk Map'); }
  function openCityBrief(city: CityProfile) { setSelectedCity(city); setSelectedCountry(countryForCity(city, countryCatalog)); setRawName(city.name); setActive('Risk Map'); }
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Shield size={18} /></div><span>Atlas Insight</span></div><nav className="nav">{nav.map(([item, Icon]) => <button key={item} className={active === item ? 'active' : ''} onClick={() => setActive(item)} title={item}><Icon size={18} /> {item}</button>)}</nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Atlas Insight Risk Map and Travel Management</div><h1>{active === 'Dashboard' ? 'Executive Overview' : active}</h1></div><div className="top-actions"><button className="pill" onClick={() => setPaid(!paid)}><UserRound size={16} /> {paid ? 'Client tier active' : 'Free tier'}</button></div></header>{active === 'Dashboard' ? <Dashboard countries={countryCatalog} setView={setActive} openAlert={openAlert} /> : null}{active === 'Risk Map' ? <RiskMapView countries={countryCatalog} selectedCountry={selectedCountry} selectedCity={selectedCity} setSelectedCountry={setSelectedCountry} setSelectedCity={setSelectedCity} rawName={rawName} setRawName={setRawName} /> : null}{active === 'Countries' ? <CountriesView countries={countryCatalog} pinned={pinnedCountries} setPinned={setPinnedCountries} openBrief={openCountryBrief} /> : null}{active === 'Cities' ? <CitiesView countries={countryCatalog} pinned={pinnedCities} setPinned={setPinnedCities} openBrief={openCityBrief} /> : null}{active === 'Alerts' ? <SimpleListView title="Alerts and Advisories">{alerts.map((alert) => <button className="feed-click" key={alert.id} onClick={() => openAlert(alert)}><strong>{alert.severity}: {alert.title}</strong><span>{alert.summary}</span><small>{alert.source} - {new Date(alert.timestamp).toLocaleString()}</small></button>)}</SimpleListView> : null}{active === 'Itineraries' ? <><AccountPanel paid={paid} setPaid={setPaid} /><TripFlow paid={paid} latestReport={latestReport} setLatestReport={setLatestReport} onTripChange={setPlannedTrip} /></> : null}{active === 'Reports' ? <SimpleListView title="Reports">{latestReport ? <ReportView report={latestReport} /> : <p className="muted">No report generated yet. Open Itineraries, create a trip, add documents, then generate a tailored report.</p>}</SimpleListView> : null}{active === 'Travel Feed' ? <TravelFeedView trip={plannedTrip} openAlert={openAlert} openTrip={() => setActive('Itineraries')} /> : null}{active === 'Support' ? <SupportView trip={plannedTrip} /> : null}{active === 'Settings' ? <SettingsView paid={paid} setPaid={setPaid} /> : null}</main></div>;
}
